session_login/config/routes.rb
Rails.application.routes.draw do
  resources :sessions, only: [:new, :create, :destroy]
  resources :users, only: [:new, :create, :show]
  resources :blogs, only: [:index, :new, :create, :show, :edit, :update, :destroy] do
    collection do
      post :confirm
    end
  end
end

session_login/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

session_login/app/models/blog.rb
class Blog < ApplicationRecord
  belongs_to :user
  validates :title, length: { minimum: 1, maximum: 75 }
  validates :content, length: { minimum: 1, maximum: 300 }
end

session_login/app/models/user.rb
class User < ApplicationRecord
  validates :name, presence: true, length: { maximum: 30 }
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }
  has_many :blogs
end

session_login/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

session_login/app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only: [:show, :edit, :destroy]
  def index
    @blogs = Blog.all
  end

  def new
    @blog = Blog.new
  end

  def create
    @blog = Blog.new(blog_params)
    @blog.user_id = current_user.id

    if params[:back]
      render :new
      return
    end

    if @blog.save
      redirect_to blogs_path, notice: "ブログを作成しました！"
    else
      render new_blog_path
    end

  end


  def confirm
    @blog = Blog.new(blog_params)
    render :new  if @blog.invalid?
  end

  def show
  end

  def edit
  end

  def update
    set_blog
    if @blog.update(blog_params)
      redirect_to blogs_path, notice: "ブログを編集しました！"
    else
      render :edit
    end
  end

  def destroy
    @blog.destroy
    redirect_to blogs_path, notice:"ブログを削除しました！"
  end

  private

  def set_blog
    @blog = Blog.find(params[:id])
  end

  def blog_params
    params.require(:blog).permit(:title, :content)
  end
end

session_login/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      redirect_to user_path(user.id)
    else
      flash.now[:danger] = "ログインに失敗しました"
      render :new
    end
  end

  def destroy
    session.delete(:user_id)
    flash[:notice] = "ログアウトしました"
    redirect_to new_session_path
  end
end

session_login/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      # 保存の成功した場合の処理
      redirect_to user_path(@user.id)
    else
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

session_login/app/helpers/application_helper.rb
module ApplicationHelper
end

session_login/app/helpers/blogs_helper.rb
module BlogsHelper
  def choose_new_or_edit
    if action_name == 'new' || action_name == 'create'
      confirm_blogs_path
    elsif action_name == 'edit'
      blog_path
    end
  end
end

session_login/app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    current_user.present?
  end
end

session_login/app/helpers/users_helper.rb
module UsersHelper
end

session_login/app/views/blogs/_form.html.erb
<%= form_with(model: @blog, local: true,url: choose_new_or_edit) do |form| %>
  <% if @blog.errors.any? %>
    <div id="error_explanation">
      <h2><%= @blog.errors.count %>件のエラーがあります。</h2>
      <ul>

        <% @blog.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="blog_title">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>
  <div class="blog_content">
    <%= form.label :content %>
    <%= form.text_field :content %>
  </div>
  <%= form.submit %>
<% end %>

<%= link_to 'ブログ一覧画面に戻る', blogs_path %>

session_login/app/views/blogs/confirm.html.erb
<h3>以下の内容で、送信する。</h3>
<%= form_with(model: @blog, url: blogs_path, local: true) do |form| %>
  <%= form.hidden_field :title %>
  <%= form.hidden_field :content %>
  <p>タイトル:<%= @blog.title %></p>
  <p>本文:<%= @blog.content %></p>
  <%= form.submit  "登録する" %>
  <%= form.submit "戻る", name: 'back' %>
<% end %>

session_login/app/views/blogs/edit.html.erb
<h2>ブログを編集する</h2>
<%= render 'form' %>

session_login/app/views/blogs/index.html.erb
<table>
  <tr>
    <th>タイトル</th>
    <th>内容</th>
    <th>ユーザ</th>
  </tr>
  <% @blogs.each do |blog| %>
  <tr>
    <td><%= blog.title %></td>
    <td><%= blog.content %></td>
    <td><%= blog.user.name %></td>
    <td><%= link_to '詳細を確認する', blog_path(id: blog.id)%></td>
    <td><%= link_to '詳細を編集する', edit_blog_path(id: blog.id)%></td>
    <td><%= link_to '削除する', blog_path(id: blog.id), method: :delete,data: { confirm: '本当に削除していいですか？' }  %></td>
  </tr>
  <% end %>

</table>
<%= link_to 'ブログ作成する', new_blog_path%>

session_login/app/views/blogs/new.html.erb
<h2>ブログを作成する</h2>
<%= render 'form' %>

session_login/app/views/blogs/show.html.erb
<table>
  <tr>
    <th>タイトル</th>
    <th>内容</th>
    <th>ユーザ</th>
  </tr>

  <tr>
    <td><%= @blog.title %></td>
    <td><%= @blog.content %></td>
    <td><%= @blog.user.name %></td>
    <td><%= link_to '内容を変更する', edit_blog_path(id: @blog.id)%></td>
  </tr>

</table>

session_login/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
  <title>SessionLogin</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
  <% flash.each do |key, value| %>
  <%= content_tag(:div, value, class: "#{key}") %>
  <% end %>

  <% if logged_in? %>
  <%= link_to "Profile", user_path(current_user.id) %>
  <%= link_to "Logout", session_path(current_user.id), method: :delete %>
  <% else %>
  <%= link_to "Sign up", new_user_path %>
  <%= link_to "Login", new_session_path %>
  <% end %>

  <%= yield %>
</body>

</html>

session_login/app/views/users/new.html.erb
<h1>Sign up</h1>
<% if @user.errors.any? %>
<div id="error_explanation">
  <h2><%= pluralize(@user.errors.count, "error") %> prohibited this @user from being saved:</h2>
  <ul>
    <% @user.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

<%= form_with(model: @user, local: true) do |f| %>
<%= f.label :name %>
<%= f.text_field :name %>

<%= f.label :email %>
<%= f.email_field :email %>

<%= f.label :password %>
<%= f.password_field :password %>

<%= f.label :password_confirmation %>
<%= f.password_field :password_confirmation %>

<%= f.submit "Create my account" %>
<% end %>

session_login/app/views/users/show.html.erb
<h1><%= @user.name %>のページ</h1>

<p>メールアドレス: <%= @user.email %></p>